name: monero_dart
description: A pure Dart solution for Monero cryptography, supporting RingCT transactions, Bulletproof Plus, multi-sig accounts, account management, and full daemon/wallet RPC support.
version: 1.6.0
homepage: "https://github.com/mrtnetwork/monero_dart"
repository: "https://github.com/mrtnetwork/monero_dart"
Author: mrhaydari.t@gmail.com
topics:
  - monero
  - wallet
  
environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  blockchain_utils: ^6.0.0



dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  flutter_lints: ^6.0.0
