name: monero_dart
description: A pure Dart solution for Monero cryptography, supporting RingCT transactions, Bulletproof Plus, multi-sig accounts, account management, and full daemon/wallet RPC support.
version: 1.4.0
homepage: "https://github.com/mrtnetwork/monero_dart"
repository: "https://github.com/mrtnetwork/monero_dart"
Author: mrhaydari.t@gmail.com
topics:
  - monero
  - wallet
  
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  blockchain_utils: ^5.2.0
  # blockchain_utils:
  #   path: ../blockchain_utils


dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  flutter_lints: ^6.0.0
